# THIS POD DEFINES A FLASK SERVICE USING A CONTAINER

apiVersion: v1

kind: Pod

metadata:
  name: myapp-devops
  labels:
    app: myapp

spec:
  containers:
    - name: flask-container
      image: pavelinux/devops
